from errno import EALREADY, EINPROGRESS, EWOULDBLOCK, ECONNRESET, EINVAL,\
    ENOTCONN, ESHUTDOWN, EINTR, EISCONN, EBADF, ECONNABORTED, EPIPE, EAGAIN,errorcode

DISCONNECTED = frozenset((ECONNRESET, ENOTCONN, ESHUTDOWN, ECONNABORTED, EPIPE, EBADF))

SHOULDCONTINUE = frozenset((EWOULDBLOCK,EAGAIN))

CONNECTING=frozenset((EWOULDBLOCK,EALREADY, EINPROGRESS))